version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  db:
    image: 'docker-proxy.tcsbank.ru/postgres:12.5'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  zookeeper:
    image: 'docker-proxy.tcsbank.ru/bitnami/zookeeper:3.7'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'docker-proxy.tcsbank.ru/bitnami/kafka:2.5.0'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
